name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Manered
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Poland

          # Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Code
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: public
          # Habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # IsoCalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Lines
          plugin_lines: yes

          # Notable
          plugin_notable: yes
          plugin_notable_from: organization

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4

#          # Traffic
#          plugin_traffic: yes
